### ISSUE TITLE
DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.

### ISSUE THREAD

**Issue by saimulhq** [abskmj/gridfile#4]
Getting this warning for mongoose version 5.12.8 and above when using gridfile.

**Comment by abskmj** [comment]
@saimulhq Could you please upgrade to version 1.1.0 and check?

**Comment by saimulhq** [comment]
@abskmj I tried after upgrading gridfile version 1.1.0 and mongoose version 5.12.11 & 5.12.12, but the problem still persists!

**Comment by abskmj** [comment]
Looks like the issue is with the mongoose module. Please refer to the configuration in [this comment](https://github.com/Automattic/mongoose/issues/9930#issuecomment-819021401) from the mongoose repo.
