### ISSUE TITLE
Could not resolve dependency: npm ERR! peer mongoose@"^5.0.0" from gridfile@1.1.1

### ISSUE THREAD

**Issue by DazDotOne** [abskmj/gridfile#7]
Thanks for this plugin, it seemed to be exactly what I was looking for however trying to install it on a fresh project using mongoose 6.1.5 results in the error

````
Found: mongoose@6.1.5
node_modules/mongoose
  mongoose@"^6.1.5" from the root project 

Could not resolve dependency:
peer mongoose@"^5.0.0" from gridfile@1.1.1
node_modules/gridfile
  gridfile@"*" from the root project
Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
````

**Comment by abskmj** [comment]
I have published a new version with a fix for this. Let me know if you are still seeing the issue.

**Comment by DazDotOne** [comment]
Thanks @abskmj I'll hopefully be picking up the project again next week so I'll be able to test and let you know.

**Comment by DazDotOne** [comment]
@abskmj Just to follow up this seems to have fixed it. Again, Thanks for your help.
