### ISSUE TITLE
Is it possible to update metadata associated with file?

### ISSUE THREAD

**Issue by DazDotOne** [abskmj/gridfile#8]
Thanks (again) for the package.

Really easy to use, loving it.

I have managed to populate the metadata field when uploading (I've changed some variable names, sorry about any funky naming):

````javascript
const upload = new Upload({
  filename: req.file.originalname,
  metadata: {
    tmpName: req.file.filename,
    version: 1
  },
});
uploaded = await upload.upload(fileStream);
````

This upload gets associated to a parent document that contains some more advanced metadata specific to how the file is used.

I would now like to add the id of the parent doc to the upload metadata. Something like this:

````javascript
Parent.create(req.body)
    .then(async (data) => {
      uploaded.metadata.template_id = data._id;

      // also tried await
      uploaded.save().then(updated => {
        return res.status(201).json(data);
      })
    })
    .catch((err) => {...});
````

Everything I've tried so far looks like it should work, I.e returning the data has the expected values in the metadata. but it doesn't actually make it to the database.

Have you come across this issue before and if so how did you tackle it?

**Comment by DazDotOne** [comment]
Interestingly, calling update on the model does work.

````javascript
Upload.updateOne({_id: uploaded._id}, {"metadata.template_id": data._id})
````

So it is workable but it would be nice to be able to hook into the Mongoose `save()` function as it means that you only have to deal with the single object in memory.

In my use-case, I'm adding the `uploaded` object to my parent (I get errors when trying to do it directly with `upload`). Being able to call `save()` would mean that any modifications I make to it can be directly reflected in my response object

**Comment by DazDotOne** [comment]
I don't have time to investigate this at the minute, I'm documenting this until I get chance to. A possible solution is by using

````
document.markModified('metadata');
````

As suggested [here](https://stackoverflow.com/a/55739214/624624).

Docs on `markModified()` are [here](https://mongoosejs.com/docs/api/document.html#document_Document-markModified).

Could be due to the underlying hydrate mechanism in the `upload()` function.

**Comment by abskmj** [comment]
Looking at the references, it doesn't seem to be an issue because of how mongoose handles changes to object data type internally. It is the expected result.

Also, you don't have to use the object returned from the `upload()` function. You can still use the original object to update the metadata. In your case, you will have to use `markModified()` whenever you update the metadata object.

**Comment by DazDotOne** [comment]
Thanks for this.

That was the route I was thinking of taking to be fair.

Hopefully I'll get to cast my eyes over it again in the next couple of days to give it a try.

**Comment by DazDotOne** [comment]
Ok so I tested this out and it does work to some extent.

Without using the object returned from `upload90` I get a `E11000 duplicate key error... index: _id_ dup key:...` because the `upload` model is still flagged as new I guess.

If I use the object returned though and use `markModified()` on the `metadata.parent_id` path it does work as expected.

I have also tried to use `upload = Upload.create(...)` which sets the `isNew` flag gets set to `false` but then the `upload()` function throws the same `E11000` error.

Thanks for the help.

I'll close the ticket but if you can think of a way to prevent Mongo from complaining about the duplicate id/mongoose considering the model as new after upload, I'd be happy to know.
